name: build pdf and epub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - make_pdf
      - feature/*
      - add_en
    paths:
      - 'ja/**'
      - 'en/**'
      - 'config-common-pdf.yaml'
      - 'epub.css'
      - 'template.tex'
      - 'build-pdf.sh'
      - 'build-epub.sh'
      - '.github/workflows/build-pdf.yaml'

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [ja, en]
    container:
      image: ghcr.io/lpi-japan/cloudnative-text:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Build PDF (${{ matrix.lang }})
        run: PDF_BUILD_MODE=direct ./build-pdf.sh ${{ matrix.lang }}
      - name: Build EPUB (${{ matrix.lang }})
        run: EPUB_BUILD_MODE=direct ./build-epub.sh ${{ matrix.lang }}
      - uses: actions/upload-artifact@v6
        with:
          name: guide-${{ matrix.lang }}
          path: |
            tmp/guide-${{ matrix.lang }}.pdf
            tmp/guide-${{ matrix.lang }}.epub
